compile:
	yacc -d class.y; \
	lex class.l; \
	gcc lex.yy.c y.tab.c -o class.exe
copy:
	cp output.xsm /home/ricky/xsm_expl/Stage-8/output.xsm
	cp final.xsm /home/ricky/xsm_expl/Stage-8/final.xsm
	cp library.lib /home/ricky/xsm_expl/library.lib