generate:
	cp library.lib /home/ak/xsm_expl/Stage-0/library.lib
	cp main.xsm /home/ak/xsm_expl/Stage-0/main.xsm
	cp exercise7.xsm /home/ak/xsm_expl/Stage-0/exercise7.xsm
	cp exercise8.xsm /home/ak/xsm_expl/Stage-0/exercise8.xsm