compile:
	yacc -d functions.y; \
	lex functions.l; \
	gcc lex.yy.c y.tab.c -o functions.exe
copy:
	cp output.xsm /home/ricky/xsm_expl/Stage-5/output.xsm
	cp final.xsm /home/ricky/xsm_expl/Stage-5/final.xsm
