generate:
	cp tf.xsm /home/ak/xsm_expl/Stage-0/tf.xsm
	cp library.lib /home/ak/xsm_expl/Stage-0/library.lib
	cp exercise1.xsm /home/ak/xsm_expl/Stage-0/exercise1.xsm
	cp exercise2.xsm /home/ak/xsm_expl/Stage-0/exercise2.xsm