generate:
	cp exercise3.xsm /home/ak/xsm_expl/Stage-0/exercise3.xsm
	cp library.lib /home/ak/xsm_expl/Stage-0/library.lib
	cp exercise4.xsm /home/ak/xsm_expl/Stage-0/exercise4.xsm
	cp exercise5.xsm /home/ak/xsm_expl/Stage-0/exercise5.xsm